# tianwan1 服务器地址
tianwan1:
  - "192.168.1.86:8901"
  - "192.168.1.86:8902"
  - "192.168.1.86:8903"
  - "192.168.1.86:8904"
  - "192.168.1.86:8905"
  - "192.168.1.86:8906"
  - "192.168.1.86:8907"
  - "192.168.1.85:8908"
  - "192.168.1.85:8909"
  - "192.168.1.85:8910"
  - "192.168.1.85:8911"
  - "192.168.1.85:8912"
  - "192.168.1.85:8913"
  - "192.168.1.85:8914"

# tianwan2 服务器地址
tianwan2:
  - "192.168.1.86:8915"
  - "192.168.1.86:8916"
  - "192.168.1.85:8917"
  - "192.168.1.85:8918"

# 告警服务器地址
alert_server: "http://192.168.1.82:80/api/account/ai/alarm"

# Excel 文件路径
excel_path: "info.xlsx"

# 需要过滤的设备名称列表
filter_map:
  # - "5M1DTW102TV"
  # - "6M2DTW101TV"
  # - "6M2DTW104TV"
  # - "5M0DTW126TV"
  # - "5M0DTW134TV"
